# Generated by Django 6.0.1 on 2026-01-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sujet',
        ),
        migrations.AddField(
            model_name='message',
            name='prenom',
            field=models.CharField(default='inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='profession',
            field=models.CharField(default='inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='message',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default='inconnu@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='Aucun message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='nom',
            field=models.CharField(default='inconnu', max_length=100),
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('places_totales', models.PositiveIntegerField()),
                ('places_reservees', models.PositiveIntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_app.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('profession', models.CharField(max_length=150)),
                ('niveau', models.CharField(help_text='Exemple : Débutant, Intermédiaire, Avancé ou déjà suivi un cours', max_length=200)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_app.sessionformation')),
            ],
            options={
                'unique_together': {('client', 'session')},
            },
        ),
    ]
